"""Versioned operating procedures and LLM price snapshot for the console.

This module is intentionally read-only.  It documents how AutoFish should operate;
it does not enable an adapter, change an automation control, or submit a platform
write.  Price data is a dated snapshot and every entry links to a primary source.
"""

from copy import deepcopy

PRICE_CHECKED_AT = "2026-08-17"


WORKFLOWS = [
    {
        "id": "source-discovery",
        "order": 1,
        "name": "货源发现与初筛",
        "stage": "选品",
        "route": "/sourcing",
        "route_label": "进入选品中心",
        "automation": "受控自动",
        "system_status": "已接入",
        "goal": "从真实供应渠道建立候选池，先排除高风险品类，再按利润、售后、库存和垂直度评分。",
        "trigger": "定时选品任务、人工关键词或以图找款请求",
        "prerequisites": ["供应商读取通道健康", "查询词或类目明确", "排除品类规则已加载"],
        "steps": [
            "调用已授权的 1688 Adapter 获取商品、SKU、价格、库存与供应商字段",
            "保存原始快照并对凭据、手机号、地址等敏感字段脱敏",
            "执行排除品类、利润空间、售后风险、运输风险和库存稳定性评分",
            "高分候选进入事实核验，低分或命中禁售规则的候选停止推进",
        ],
        "evidence": ["来源 URL", "Adapter 名称与版本", "抓取时间", "原始快照哈希", "评分拆解"],
        "stop_conditions": [
            "供应商授权失效",
            "来源页不可访问",
            "命中禁售/高风险品类",
            "关键字段缺失",
        ],
        "acceptance": "候选具有可追溯来源、至少一个真实 SKU、价格区间和明确筛选结论。",
    },
    {
        "id": "supplier-fact-check",
        "order": 2,
        "name": "供应事实核验",
        "stage": "选品",
        "route": "/clawhub",
        "route_label": "进入 1688 能力台",
        "automation": "人机协同",
        "system_status": "已接入",
        "goal": "确认库存、运费、规格、交期、退换条件和供货稳定性，不用推测替代事实。",
        "trigger": "候选达到导入分数线，或价格/库存快照超过时效",
        "prerequisites": ["候选已保存", "供应商与 SKU 标识完整", "询价问题模板可用"],
        "steps": [
            "读取商品详情和 SKU 阶梯价，区分样品价、起批价与实际可采购价",
            "核对运费、库存、发货地、预计时效、破损与退换规则",
            "必要时生成结构化询价清单，由操作员在授权页面发送",
            "将核验时间、证据说明和变化字段回写候选事实",
        ],
        "evidence": ["SKU 事实", "运费", "库存", "发货时效", "售后条款", "核验时间"],
        "stop_conditions": [
            "价格需登录后才可见但会话失效",
            "供应商答复含糊",
            "最低采购量不匹配",
            "库存不稳定",
        ],
        "acceptance": "用于定价和文案的每个关键结论都能指向当次真实快照或人工核验记录。",
    },
    {
        "id": "catalog-pricing",
        "order": 3,
        "name": "商品建档与定价",
        "stage": "商品",
        "route": "/products",
        "route_label": "进入商品中心",
        "automation": "受控自动",
        "system_status": "已接入",
        "goal": "把供应事实转换为内部商品与 SKU，并用完整成本计算最低价和建议售价。",
        "trigger": "事实核验通过的候选准备导入",
        "prerequisites": ["供应商和 SKU 事实完整", "成本参数有效", "候选未命中排除规则"],
        "steps": [
            "生成内部商品编码并关联供应商、来源快照和 SKU",
            "计算货品成本、运费、平台费用、售后准备金和最低利润",
            "输出最低销售价、目标销售价、建议售价与预期利润",
            "价格低于底线或变动超阈值时创建人工价格复核任务",
        ],
        "evidence": ["成本分项", "定价公式版本", "最低价", "目标价", "利润快照"],
        "stop_conditions": ["成本字段缺失", "计算结果低于利润底线", "供应价格异常跳变"],
        "acceptance": "每个可发布 SKU 都有可解释的价格底线，任何自动调价都不能穿透该底线。",
    },
    {
        "id": "premium-images",
        "order": 4,
        "name": "精品图片制作与质检",
        "stage": "素材",
        "route": "/xianyu",
        "route_label": "查看闲鱼商品",
        "automation": "人机协同",
        "system_status": "受控执行",
        "goal": "基于真实商品形态生成干净、统一、可信的精品主图和详情图，不虚构功能或配件。",
        "trigger": "商品建档完成，或存量商品需要升级图片",
        "prerequisites": ["有权使用的原始商品图", "真实规格和配件清单", "图片风格规范"],
        "steps": [
            "检查原图清晰度、主体完整性、水印、商标和背景杂物",
            "按商品真实外观做高清化、构图、光影和背景优化",
            "生成主图、场景图、细节图和规格说明图，统一色温与留白",
            "用视觉模型复核变形、错字、虚构配件、品牌侵权和平台禁限信息",
            "将新素材与来源图、生成参数和质检结果关联保存",
        ],
        "evidence": ["来源图", "处理版本", "生成参数", "视觉质检结论", "素材清单"],
        "stop_conditions": [
            "原图权利不明",
            "生成图改变商品结构",
            "出现无法确认的品牌或参数",
            "图片文字错误",
        ],
        "acceptance": "图片清晰统一且与实物事实一致；不存在承诺、功能或配件层面的视觉误导。",
    },
    {
        "id": "owner-copy",
        "order": 5,
        "name": "货主口吻文案与禁词检查",
        "stage": "素材",
        "route": "/clawhub",
        "route_label": "进入草稿管线",
        "automation": "受控自动",
        "system_status": "已接入",
        "goal": "使用自然的货主口吻描述真实商品，避免暴露供应链模式或生成无法兑现的承诺。",
        "trigger": "图片通过质检，准备生成发布草稿",
        "prerequisites": ["商品事实完整", "售价已确定", "发布文案策略已加载"],
        "steps": [
            "从商品事实生成标题、卖点、规格、成色/状态、发货与售后说明",
            "执行事实一致性检查，删除未在来源中出现的性能、材质和赠品",
            "拦截一键代发、支持代发货、一件发货、货源直发等供应链暴露词",
            "检查极限词、站外引流、品牌混淆和不合理时效承诺",
            "保存草稿版本、校验结果和使用的事实快照",
        ],
        "evidence": ["草稿版本", "事实字段映射", "禁词扫描结果", "改写记录"],
        "stop_conditions": [
            "存在无法核实的卖点",
            "命中硬性禁词",
            "规格与图片冲突",
            "售价未通过底线",
        ],
        "acceptance": "文案以货主视角自然表达，不包含代发暗示，且每项核心描述都有事实依据。",
    },
    {
        "id": "xianyu-publish",
        "order": 6,
        "name": "闲鱼发布、确认与回填",
        "stage": "发布",
        "route": "/xianyu-workbench",
        "route_label": "进入闲鱼工作台",
        "automation": "受控写入",
        "system_status": "受控执行",
        "goal": "在复用登录会话的授权页面完成字段预填、最终核验和发布，并把真实平台结果回填系统。",
        "trigger": "草稿、图片、价格和账号门禁全部通过",
        "prerequisites": ["闲鱼登录有效", "发布范围已授权", "草稿校验通过", "价格未过期"],
        "steps": [
            "Browser Bridge 创建带幂等键的发布预览任务",
            "打开卖家页面并预填标题、描述、价格、类目和图片",
            "提交前重新读取页面字段，执行价格、禁词、图片数量和账号检查",
            "仅在控制策略允许时执行最终提交；验证码、人脸或风控提示立即转人工",
            "读取平台商品 ID、状态和 URL，回填系统并保存页面证据",
        ],
        "evidence": ["动作预览", "幂等键", "提交前字段快照", "平台商品 ID", "结果 URL", "审计日志"],
        "stop_conditions": [
            "验证码/人脸",
            "登录失效",
            "平台字段变化",
            "价格冲突",
            "响应结果不确定",
        ],
        "acceptance": "平台真实可见且系统状态一致；重复执行不会生成第二个商品。",
    },
    {
        "id": "customer-service",
        "order": 7,
        "name": "问价、咨询与 AI 回复",
        "stage": "交易",
        "route": "/conversations",
        "route_label": "进入 AI 客服",
        "automation": "受控自动",
        "system_status": "受控执行",
        "goal": "基于商品、库存、价格和售后事实快速回复；议价越界或高风险意图转人工。",
        "trigger": "收到新消息或未回复会话进入轮询",
        "prerequisites": ["会话已关联商品", "事实快照在有效期内", "客服策略和价格底线可用"],
        "steps": [
            "识别问价、规格、库存、时效、售后、投诉或其他意图",
            "只读取数据库和最新外部快照，不凭空补充商品事实",
            "生成结构化回复建议并检查最低价、承诺、隐私和敏感词",
            "普通问题可在限额内自动发送；砍价越界、纠纷、辱骂、隐私或不确定事实转人工",
            "记录模型、输入哈希、输出、发送结果和会话状态",
        ],
        "evidence": ["意图", "引用事实", "回复建议", "策略结论", "平台发送结果", "模型用量"],
        "stop_conditions": [
            "事实过期",
            "价格低于底线",
            "投诉/纠纷",
            "隐私信息",
            "模型输出校验失败",
        ],
        "acceptance": "自动回复可解释、可追溯且不越权；人工接管后 AI 不再发送。",
    },
    {
        "id": "order-sync",
        "order": 8,
        "name": "订单识别与事实同步",
        "stage": "履约",
        "route": "/orders",
        "route_label": "进入订单",
        "automation": "只读自动",
        "system_status": "已接入",
        "goal": "同步真实订单状态、商品、金额和收货事实，避免重复建单或把未付款订单推进采购。",
        "trigger": "订单轮询、平台事件回调或人工刷新",
        "prerequisites": ["账号授权有效", "订单读取通道健康", "商品映射可用"],
        "steps": [
            "按外部订单 ID 幂等拉取订单和状态",
            "关联闲鱼商品、内部商品与 SKU，核对成交价是否低于底线",
            "区分待付款、已付款、已关闭、退款中和售后状态",
            "仅已付款且事实完整的订单生成采购预览",
        ],
        "evidence": ["外部订单 ID", "订单状态快照", "金额", "商品映射", "同步时间"],
        "stop_conditions": ["订单状态不确定", "商品无法映射", "成交价异常", "收货事实缺失"],
        "acceptance": "订单状态与平台一致，重复回调不重复建单，未付款订单绝不进入采购。",
    },
    {
        "id": "purchase",
        "order": 9,
        "name": "采购预览与供应商下单",
        "stage": "履约",
        "route": "/purchases",
        "route_label": "进入采购任务",
        "automation": "人工确认",
        "system_status": "需人工",
        "goal": "为已付款订单生成准确采购预览；支付属于高风险动作，默认保留人工确认。",
        "trigger": "订单已付款且通过利润、库存和地址检查",
        "prerequisites": ["订单已付款", "SKU 映射唯一", "库存和价格已二次核验", "收货信息完整"],
        "steps": [
            "重新读取供应商 SKU、库存、单价、运费和预计发货时间",
            "计算实际采购成本并复核订单利润，不符合阈值则转人工",
            "生成采购清单和幂等键，在授权供应商页面预填 SKU、数量与地址",
            "操作员核对并完成支付；系统记录采购单号和实际成本",
        ],
        "evidence": ["二次价格快照", "采购预览", "收货字段校验", "供应商订单号", "实际成本"],
        "stop_conditions": ["库存不足", "涨价导致亏损", "地址不完整", "SKU 不唯一", "支付步骤"],
        "acceptance": "订单、SKU、地址和金额完全一致；支付前必须有清晰的最终采购预览。",
    },
    {
        "id": "logistics",
        "order": 10,
        "name": "物流单号核验与发货同步",
        "stage": "履约",
        "route": "/logistics",
        "route_label": "进入物流",
        "automation": "受控写入",
        "system_status": "受控执行",
        "goal": "从真实供应订单获取承运商和运单号，核验后同步到闲鱼，不伪造物流。",
        "trigger": "供应商订单产生运单或状态变化",
        "prerequisites": ["采购单与闲鱼订单映射唯一", "真实运单已产生", "承运商可识别"],
        "steps": [
            "读取供应商订单的真实承运商、运单号和揽收状态",
            "校验运单格式、订单映射和重复使用情况",
            "生成闲鱼发货预览，在策略允许时回填真实物流信息",
            "保存平台结果并持续同步揽收、运输、签收和异常状态",
        ],
        "evidence": ["供应商订单号", "真实运单", "承运商", "闲鱼发货结果", "物流轨迹"],
        "stop_conditions": [
            "无真实运单",
            "运单已用于其他订单",
            "承运商未知",
            "平台拒绝或结果不确定",
        ],
        "acceptance": "供应商、系统和闲鱼的订单与运单一一对应，状态可追溯且没有虚假发货。",
    },
    {
        "id": "aftersales",
        "order": 11,
        "name": "售后、退款与纠纷接管",
        "stage": "售后",
        "route": "/risk",
        "route_label": "进入风险与人工",
        "automation": "人工接管",
        "system_status": "需人工",
        "goal": "快速聚合订单、聊天、商品、物流和供应商证据，辅助操作员处理退款和纠纷。",
        "trigger": "退款申请、投诉、拒收、破损、错发或平台争议",
        "prerequisites": ["订单事实完整", "会话和物流证据可读取", "人工任务已创建"],
        "steps": [
            "停止该订单相关的自动回复、自动发货和后续写动作",
            "汇总成交、商品描述、聊天、物流、供应商售后与图片证据",
            "AI 只生成事实摘要和处理选项，不自动承诺退款或责任归属",
            "操作员决定方案并在平台执行，系统记录结果与真实损益",
        ],
        "evidence": ["完整时间线", "订单和聊天快照", "物流证明", "供应商条款", "人工结论"],
        "stop_conditions": ["出现纠纷即停止自动动作", "证据冲突", "涉及大额退款或法律问题"],
        "acceptance": "人工能在一个任务中看到全部事实；退款、拒绝或赔付均由人明确决定。",
    },
    {
        "id": "daily-operations",
        "order": 12,
        "name": "日常巡检、异常与人工任务",
        "stage": "运维",
        "route": "/tasks",
        "route_label": "进入任务中心",
        "automation": "受控自动",
        "system_status": "已接入",
        "goal": "把登录失效、库存波动、价格越界、同步失败和未决售后统一转成可处理任务。",
        "trigger": "定时巡检、连续失败熔断或业务规则触发",
        "prerequisites": ["调度器健康", "审计日志可写", "通知与人工队列可用"],
        "steps": [
            "检查服务、数据库、Redis、Adapter、登录会话和调度器健康",
            "扫描价格、库存、订单、物流、发布和客服任务的过期或异常状态",
            "连续失败达到阈值时熔断对应自动化范围并创建高优先级任务",
            "操作员处理后记录证据并恢复最小必要范围，先 REVIEW 再 AUTOMATIC",
        ],
        "evidence": ["健康检查", "失败计数", "熔断范围", "人工处理记录", "恢复审计"],
        "stop_conditions": [
            "数据库或 Redis 不可用",
            "Adapter 授权失效",
            "平台风控",
            "结果状态不确定",
        ],
        "acceptance": "任何异常都有明确负责人、状态和证据；恢复操作不绕过 REVIEW 验证。",
    },
    {
        "id": "adversarial-testing",
        "order": 13,
        "name": "对抗性测试与上线门禁",
        "stage": "质量",
        "route": "/settings",
        "route_label": "进入系统设置",
        "automation": "人工验收",
        "system_status": "受控执行",
        "goal": "在小流量中验证重复提交、过期事实、模型越权、页面变化和外部失败不会造成失控写入。",
        "trigger": "版本升级、Adapter 变化、模型切换或准备扩大自动化范围",
        "prerequisites": ["测试账户/可回滚数据", "自动化处于 REVIEW", "审计和紧急停止可用"],
        "steps": [
            "执行正常路径、重复请求、超时、断网、限流、登录失效和页面字段变化测试",
            "注入禁词、低于底价、虚构事实、提示词攻击和恶意客服消息",
            "验证幂等、熔断、人工接管、审计完整性和停止所有自动化",
            "只有真实小流量验收通过后才逐范围提高限额或切换 AUTOMATIC",
        ],
        "evidence": ["测试用例", "预期与实际", "审计日志", "缺陷记录", "验收结论"],
        "stop_conditions": [
            "出现未审计写入",
            "重复发布/回复/发货",
            "价格底线被绕过",
            "无法紧急停止",
        ],
        "acceptance": "关键对抗场景全部通过，已知风险有隔离或人工边界，才允许扩大自动化。",
    },
    {
        "id": "nas-operations",
        "order": 14,
        "name": "NAS 部署、备份与恢复",
        "stage": "运维",
        "route": "/settings",
        "route_label": "查看系统控制面",
        "automation": "受控运维",
        "system_status": "已接入",
        "goal": "在 NAS 上以最小权限运行容器，保持数据、凭据、日志和备份可恢复。",
        "trigger": "版本发布、配置变更、定期备份校验或故障恢复",
        "prerequisites": ["部署目录和备份目标明确", "环境变量与凭据文件已挂载", "旧版本可回退"],
        "steps": [
            "在本地完成后端测试、静态检查、前端类型检查和生产构建",
            "仅同步本次变更文件到 NAS，构建受影响的容器镜像",
            "执行数据库迁移并滚动更新，等待 health/ready 通过",
            "验证登录、核心 API 和关键页面；检查容器日志没有新错误",
            "每日生成 PostgreSQL 自包含备份并按保留期清理，定期做恢复演练",
        ],
        "evidence": ["测试结果", "镜像与版本", "健康检查", "部署日志", "备份文件", "恢复演练"],
        "stop_conditions": ["本地测试失败", "迁移不可逆且无备份", "健康检查失败", "核心页面回归"],
        "acceptance": "服务健康、页面可用、备份有效；升级失败时能够恢复数据库和上一个可运行版本。",
    },
]


MODEL_PROVIDERS = [
    {
        "id": "openai-luna",
        "provider": "OpenAI",
        "model": "GPT-5.6 Luna",
        "currency": "USD",
        "input_per_million": 0.20,
        "output_per_million": 1.20,
        "cached_input_per_million": 0.02,
        "context_tokens": 1_050_000,
        "structured_output": True,
        "tool_calling": True,
        "vision_input": True,
        "image_generation": "同一厂商的 GPT Image 2",
        "availability": "需验证 NAS 到官方 API 的网络、账户与结算可用性",
        "fit_score": 96,
        "cost_score": 95,
        "recommendation": "单一厂商首选",
        "notes": "覆盖中文文本、图片理解、函数调用和长上下文；精品图使用同厂商图像模型。",
        "source_url": "https://developers.openai.com/api/docs/models",
        "pricing_url": "https://developers.openai.com/api/docs/pricing",
    },
    {
        "id": "deepseek-v4-flash",
        "provider": "DeepSeek",
        "model": "DeepSeek V4 Flash",
        "currency": "USD",
        "input_per_million": 0.44,
        "output_per_million": 1.32,
        "cached_input_per_million": 0.014,
        "offpeak_input_per_million": 0.22,
        "offpeak_output_per_million": 0.66,
        "context_tokens": 1_000_000,
        "structured_output": True,
        "tool_calling": True,
        "vision_input": False,
        "image_generation": "不覆盖",
        "availability": "国内接入便利；低谷时段成本最低",
        "fit_score": 78,
        "cost_score": 98,
        "recommendation": "纯文本低谷任务首选",
        "notes": (
            "JSON、工具调用及 OpenAI/Anthropic/Responses 格式兼容；"
            "不能单独承担图片理解和精品图生成。"
        ),
        "source_url": "https://api-docs.deepseek.com/quick_start/pricing/",
        "pricing_url": "https://api-docs.deepseek.com/quick_start/pricing/",
    },
    {
        "id": "qwen37-plus",
        "provider": "阿里云百炼",
        "model": "Qwen3.7 Plus",
        "currency": "CNY",
        "input_per_million": 2.00,
        "output_per_million": 8.00,
        "cached_input_per_million": None,
        "context_tokens": 1_000_000,
        "structured_output": True,
        "tool_calling": True,
        "vision_input": True,
        "image_generation": "需搭配同厂商图像模型",
        "availability": "国内部署、付款和网络链路友好",
        "fit_score": 91,
        "cost_score": 90,
        "recommendation": "国内单厂商备选",
        "notes": "中文、视觉和工具生态完整；价格按中国内地 <=256K 输入档位的公开标价快照计算。",
        "source_url": "https://help.aliyun.com/zh/model-studio/models",
        "pricing_url": "https://help.aliyun.com/en/model-studio/model-pricing",
    },
    {
        "id": "gemini31-flash-lite",
        "provider": "Google",
        "model": "Gemini 3.1 Flash-Lite Preview",
        "currency": "USD",
        "input_per_million": 0.25,
        "output_per_million": 1.50,
        "cached_input_per_million": None,
        "context_tokens": 1_000_000,
        "structured_output": True,
        "tool_calling": True,
        "vision_input": True,
        "image_generation": "需搭配 Gemini 图像模型",
        "availability": "Preview；生产可用性和 NAS 网络需专项验证",
        "fit_score": 87,
        "cost_score": 92,
        "recommendation": "多模态候选",
        "notes": "价格低且多模态完整，但当前为预览版本，不作为无人值守主路由。",
        "source_url": "https://ai.google.dev/gemini-api/docs/gemini-3",
        "pricing_url": "https://ai.google.dev/gemini-api/docs/pricing",
    },
    {
        "id": "claude-haiku45",
        "provider": "Anthropic",
        "model": "Claude Haiku 4.5",
        "currency": "USD",
        "input_per_million": 1.00,
        "output_per_million": 5.00,
        "cached_input_per_million": 0.10,
        "context_tokens": 200_000,
        "structured_output": True,
        "tool_calling": True,
        "vision_input": True,
        "image_generation": "不覆盖",
        "availability": "需验证账户、区域和 NAS 网络",
        "fit_score": 84,
        "cost_score": 70,
        "recommendation": "非成本优先",
        "notes": "文本与视觉能力可用，但相同业务量的公开标价明显高于本次首选。",
        "source_url": "https://platform.claude.com/docs/en/about-claude/models/overview",
        "pricing_url": "https://platform.claude.com/docs/en/about-claude/pricing",
    },
]


MODEL_STRATEGY = {
    "decision": "分层路由优于单模型包办",
    "single_provider": {
        "name": "最省运维的完整方案",
        "primary": "GPT-5.6 Luna",
        "image": "GPT Image 2",
        "why": (
            "同一厂商即可覆盖结构化中文、客服、工具调用、视觉质检和精品图生成；"
            "Luna 的标准文本单价也处于本次比较的低位。"
        ),
    },
    "lowest_cost": {
        "name": "最低综合成本方案",
        "primary": "GPT-5.6 Luna",
        "offpeak_text": "DeepSeek V4 Flash",
        "image": "GPT Image 2",
        "why": (
            "在线客服与视觉走 Luna；可延迟的批量文案、分类和摘要在 DeepSeek 低谷时段运行；"
            "图片只在商品上新或重做时调用图像模型。"
        ),
    },
    "domestic": {
        "name": "国内链路优先方案",
        "primary": "Qwen3.7 Plus",
        "image": "阿里云同厂商图像模型",
        "why": (
            "便于国内网络、账户和人民币结算；上线前仍需用 AutoFish 固定测试集验证 JSON "
            "稳定性、视觉事实一致性和中文客服质量。"
        ),
    },
    "routing": [
        {
            "task": "意图分类、字段抽取、普通问答",
            "route": "GPT-5.6 Luna",
            "fallback": "DeepSeek V4 Flash（低谷批处理）",
        },
        {
            "task": "商品图识别、生成图事实质检",
            "route": "GPT-5.6 Luna",
            "fallback": "Qwen3.7 Plus Vision",
        },
        {
            "task": "标题、详情、客服回复草稿",
            "route": "GPT-5.6 Luna",
            "fallback": "DeepSeek V4 Flash",
        },
        {
            "task": "精品主图和场景图生成",
            "route": "GPT Image 2",
            "fallback": "国内图像模型人工验收",
        },
        {
            "task": "退款、纠纷、价格越界、事实冲突",
            "route": "人工接管",
            "fallback": "AI 仅做事实摘要",
        },
    ],
    "cost_controls": [
        "用 JSON Schema 限制输出长度，失败只重试一次，第二次直接转人工",
        "商品事实和固定策略使用提示缓存；会话只传递必要的最近消息与结构化摘要",
        "可延迟任务使用 Batch/Flex 或 DeepSeek 低谷时段，不为离线任务支付实时溢价",
        "视觉模型先做低成本质检，只有异常样本才升级人工；图像生成按商品而非按会话调用",
        "记录 provider、model、输入/输出 token、缓存命中、耗时、任务和成本，按周复盘路由",
    ],
    "production_gate": [
        "准备固定的中文客服、商品事实、禁词、价格底线、图片一致性和提示词攻击测试集",
        "候选模型分别跑至少 200 个结构化样本；Schema 一次通过率目标 >= 99%",
        "事实幻觉率必须为 0；价格、退款、纠纷等高风险决策始终由确定性规则或人工决定",
        "影子运行 7 天并比较质量、P95 延迟、每千任务成本和人工接管率，再切换生产路由",
    ],
}


DEFAULT_SCENARIO = {
    "name": "月度常规运营参考",
    "input_million_tokens": 12,
    "output_million_tokens": 2.4,
    "usd_to_cny": 7.2,
    "assumptions": [
        "约 10,000 次客服/分类任务，加 100 个商品的文案与质检",
        "仅比较文本 token；图片生成按尺寸、质量和图像 token 另计",
        "汇率 7.20 仅为可编辑预算参数，不代表实时结算汇率",
        "标准价不含税、网络、存储、搜索工具和第三方渠道加价",
    ],
}


GUARDRAILS = [
    "大模型只生成结构化建议；价格底线、禁词、权限、限额、幂等和熔断由确定性代码执行。",
    "验证码、人脸、设备验证、平台风控、退款、支付和纠纷永远进入人工任务。",
    "页面中展示的模型价格是 2026-08-17 官方快照，不会自动配置 API Key 或启用外部调用。",
    "模型或价格变更必须先更新快照并通过固定评测集，不能直接替换生产路由。",
]


def get_operations_guide() -> dict:
    """Return a detached copy so callers cannot mutate the process registry."""

    return deepcopy(
        {
            "version": "2026.08.17-1",
            "price_checked_at": PRICE_CHECKED_AT,
            "workflow_count": len(WORKFLOWS),
            "workflows": WORKFLOWS,
            "model_providers": MODEL_PROVIDERS,
            "model_strategy": MODEL_STRATEGY,
            "default_scenario": DEFAULT_SCENARIO,
            "guardrails": GUARDRAILS,
        }
    )
