"""initial phase 0 to 2 schema

Revision ID: fe07d1b0cd73
Revises:
Create Date: 2026-08-15 20:35:38.183330
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "fe07d1b0cd73"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "SYNC_SUPPLIER_PRICE",
                "SYNC_SUPPLIER_STOCK",
                "GENERATE_PRODUCT",
                "PUBLISH_PRODUCT",
                "SYNC_MESSAGES",
                "REPLY_MESSAGE",
                "SYNC_ORDERS",
                "CREATE_PURCHASE",
                "SYNC_LOGISTICS",
                "ANALYZE_SKU",
                name="jobtype",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "RETRY",
                "SUCCEEDED",
                "FAILED",
                "MANUAL_REQUIRED",
                "CANCELLED",
                name="jobstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=180), nullable=False),
        sa.Column("correlation_id", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("result_summary", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_automation_jobs_idempotency_key")),
    )
    op.create_index(
        op.f("ix_automation_jobs_correlation_id"),
        "automation_jobs",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_automation_jobs_type"), "automation_jobs", ["type"], unique=False)
    op.create_index(
        "ix_jobs_status_schedule", "automation_jobs", ["status", "scheduled_at"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("external_customer_id", sa.String(length=160), nullable=False),
        sa.Column("display_name_masked", sa.String(length=160), nullable=True),
        sa.Column("risk_level", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(
        op.f("ix_customers_external_customer_id"),
        "customers",
        ["external_customer_id"],
        unique=False,
    )
    op.create_table(
        "pricing_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("platform_fee_rate", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("fixed_platform_fee", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("after_sales_reserve", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("minimum_profit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("negotiation_margin", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_rules")),
    )
    op.create_index(op.f("ix_pricing_rules_category"), "pricing_rules", ["category"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("internal_code", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("category", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("images", sa.JSON(), nullable=False),
        sa.Column("compatibility", sa.JSON(), nullable=False),
        sa.Column(
            "lifecycle",
            sa.Enum(
                "CANDIDATE",
                "TESTING",
                "ACTIVE",
                "WINNER",
                "DECLINING",
                "PAUSED",
                "REMOVED",
                name="lifecycle",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "xianyu_status",
            sa.Enum(
                "UNPUBLISHED",
                "REVIEW_PENDING",
                "ACTIVE",
                "PAUSED",
                "REMOVED",
                name="xianyustatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("excluded_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    op.create_index(op.f("ix_products_internal_code"), "products", ["internal_code"], unique=True)
    op.create_index(op.f("ix_products_lifecycle"), "products", ["lifecycle"], unique=False)
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("credential_ref", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
    )
    op.create_index(op.f("ix_suppliers_code"), "suppliers", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("external_account_id", sa.String(length=160), nullable=True),
        sa.Column("nickname", sa.String(length=160), nullable=False),
        sa.Column("credential_ref", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_accounts_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_index(
        "ix_accounts_platform_external",
        "accounts",
        ["platform", "external_account_id"],
        unique=False,
    )
    op.create_table(
        "adapter_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("automation_job_id", sa.Integer(), nullable=True),
        sa.Column("correlation_id", sa.String(length=80), nullable=False),
        sa.Column("adapter", sa.String(length=100), nullable=False),
        sa.Column("adapter_version", sa.String(length=80), nullable=True),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("raw_snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("safe_summary", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["automation_job_id"],
            ["automation_jobs.id"],
            name=op.f("fk_adapter_calls_automation_job_id_automation_jobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adapter_calls")),
    )
    op.create_index(
        "ix_adapter_calls_adapter_created", "adapter_calls", ["adapter", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_adapter_calls_correlation_id"), "adapter_calls", ["correlation_id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=True),
        sa.Column("before_data", sa.JSON(), nullable=False),
        sa.Column("after_data", sa.JSON(), nullable=False),
        sa.Column("result", sa.String(length=40), nullable=False),
        sa.Column("correlation_id", sa.String(length=80), nullable=False),
        sa.Column("ip_address", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_correlation_id"), "audit_logs", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_entity_created",
        "audit_logs",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "automation_controls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "GLOBAL",
                "PUBLISH",
                "CUSTOMER_SERVICE",
                "PURCHASE",
                "REPRICING",
                name="automationscope",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("stopped_reason", sa.String(length=500), nullable=True),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_automation_controls_updated_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_controls")),
        sa.UniqueConstraint("scope", name=op.f("uq_automation_controls_scope")),
    )
    op.create_table(
        "manual_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("automation_job_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.String(length=100), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["automation_job_id"],
            ["automation_jobs.id"],
            name=op.f("fk_manual_tasks_automation_job_id_automation_jobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_tasks")),
    )
    op.create_index(
        "ix_manual_tasks_status_priority", "manual_tasks", ["status", "priority"], unique=False
    )
    op.create_table(
        "product_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("profit_space", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("after_sales_safety", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("fault_safety", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("compatibility_safety", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("transport_safety", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("stock_stability", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("price_stability", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("verticality", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("total_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("weights", sa.JSON(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_scores_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_scores")),
    )
    op.create_index(
        "ix_product_scores_product_created",
        "product_scores",
        ["product_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_scores_total_score"), "product_scores", ["total_score"], unique=False
    )
    op.create_table(
        "product_skus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("sku_code", sa.String(length=120), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("supplier_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("supplier_shipping", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("platform_fee", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("after_sales_reserve", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("minimum_profit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("target_profit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("negotiation_margin", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("final_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("minimum_sale_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("recommended_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("current_sale_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("expected_profit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_skus_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_skus")),
    )
    op.create_index(op.f("ix_product_skus_score"), "product_skus", ["score"], unique=False)
    op.create_index(op.f("ix_product_skus_sku_code"), "product_skus", ["sku_code"], unique=True)
    op.create_table(
        "supplier_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("external_product_id", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("category", sa.String(length=200), nullable=False),
        sa.Column("supplier_name", sa.String(length=200), nullable=True),
        sa.Column("external_supplier_id", sa.String(length=160), nullable=True),
        sa.Column("raw_snapshot", sa.JSON(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplier_products_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_products")),
        sa.UniqueConstraint(
            "supplier_id", "external_product_id", name="uq_supplier_product_external"
        ),
    )
    op.create_index(
        op.f("ix_supplier_products_snapshot_hash"),
        "supplier_products",
        ["snapshot_hash"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("external_conversation_id", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("manual_mode", sa.Boolean(), nullable=False),
        sa.Column("manual_reason", sa.String(length=300), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_conversations_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_conversations_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_conversations_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        "ix_conversations_account_external",
        "conversations",
        ["account_id", "external_conversation_id"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("external_order_id", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "PAID",
                "SUPPLIER_CHECK",
                "PURCHASE_PENDING",
                "PURCHASED",
                "SUPPLIER_SHIPPED",
                "XIANYU_SHIPPED",
                "DELIVERED",
                "COMPLETED",
                "OUT_OF_STOCK",
                "PRICE_CHANGED",
                "PURCHASE_FAILED",
                "ADDRESS_ERROR",
                "LOGISTICS_ERROR",
                "AFTERSALES",
                "REFUND_PENDING",
                "DISPUTE",
                "MANUAL_REQUIRED",
                name="orderstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("revenue", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("expected_profit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("actual_profit", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("buyer_name_encrypted", sa.Text(), nullable=True),
        sa.Column("buyer_phone_encrypted", sa.Text(), nullable=True),
        sa.Column("buyer_address_encrypted", sa.Text(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_orders_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_orders_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("external_order_id", name=op.f("uq_orders_external_order_id")),
    )
    op.create_index(
        "ix_orders_account_status_created",
        "orders",
        ["account_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "publication_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=180), nullable=False),
        sa.Column("requested_by_user_id", sa.Integer(), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_publication_tasks_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_publication_tasks_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_publication_tasks_requested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication_tasks")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_publication_tasks_idempotency_key")),
        sa.UniqueConstraint("product_id", "status", name="uq_publication_product_status"),
    )
    op.create_table(
        "supplier_skus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_product_id", sa.Integer(), nullable=False),
        sa.Column("external_sku_id", sa.String(length=160), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("stock_status", sa.String(length=40), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["supplier_product_id"],
            ["supplier_products.id"],
            name=op.f("fk_supplier_skus_supplier_product_id_supplier_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_skus")),
        sa.UniqueConstraint(
            "supplier_product_id", "external_sku_id", name="uq_supplier_sku_external"
        ),
    )
    op.create_table(
        "xianyu_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("external_product_id", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("published_title", sa.String(length=500), nullable=True),
        sa.Column("published_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_xianyu_products_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_xianyu_products_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_xianyu_products")),
        sa.UniqueConstraint("account_id", "external_product_id", name="uq_xianyu_product_external"),
    )
    op.create_table(
        "after_sales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_after_sales_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_after_sales")),
    )
    op.create_table(
        "ai_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent", sa.String(length=60), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("input_context_hash", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("reason_summary", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_ai_decisions_conversation_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_ai_decisions_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_ai_decisions_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_decisions")),
    )
    op.create_index(
        "ix_ai_decisions_agent_created", "ai_decisions", ["agent", "created_at"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("external_message_id", sa.String(length=160), nullable=True),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=40), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("sent_by_ai", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_external_message_id"), "messages", ["external_message_id"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_sku_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_sale_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("supplier_cost_snapshot", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("shipping_snapshot", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("platform_fee_snapshot", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reserve_snapshot", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_sku_id"],
            ["product_skus.id"],
            name=op.f("fk_order_items_product_sku_id_product_skus"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_table(
        "product_price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_sku_id", sa.Integer(), nullable=False),
        sa.Column("supplier_sku_id", sa.Integer(), nullable=True),
        sa.Column("supplier_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("recommended_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_sku_id"],
            ["product_skus.id"],
            name=op.f("fk_product_price_history_product_sku_id_product_skus"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_sku_id"],
            ["supplier_skus.id"],
            name=op.f("fk_product_price_history_supplier_sku_id_supplier_skus"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_price_history")),
    )
    op.create_index(
        "ix_price_history_sku_checked",
        "product_price_history",
        ["product_sku_id", "checked_at"],
        unique=False,
    )
    op.create_table(
        "product_stock_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_sku_id", sa.Integer(), nullable=False),
        sa.Column("supplier_sku_id", sa.Integer(), nullable=True),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("stock_status", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_sku_id"],
            ["product_skus.id"],
            name=op.f("fk_product_stock_history_product_sku_id_product_skus"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_sku_id"],
            ["supplier_skus.id"],
            name=op.f("fk_product_stock_history_supplier_sku_id_supplier_skus"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_stock_history")),
    )
    op.create_index(
        "ix_stock_history_sku_checked",
        "product_stock_history",
        ["product_sku_id", "checked_at"],
        unique=False,
    )
    op.create_table(
        "product_supplier_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_sku_id", sa.Integer(), nullable=False),
        sa.Column("supplier_sku_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_sku_id"],
            ["product_skus.id"],
            name=op.f("fk_product_supplier_links_product_sku_id_product_skus"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_sku_id"],
            ["supplier_skus.id"],
            name=op.f("fk_product_supplier_links_supplier_sku_id_supplier_skus"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_supplier_links")),
        sa.UniqueConstraint("product_sku_id", "supplier_sku_id", name="uq_product_supplier_link"),
    )
    op.create_table(
        "supplier_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("external_order_id", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("payload_snapshot", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_supplier_orders_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplier_orders_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_orders")),
    )
    op.create_index(
        op.f("ix_supplier_orders_external_order_id"),
        "supplier_orders",
        ["external_order_id"],
        unique=False,
    )
    op.create_table(
        "shipments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_order_id", sa.Integer(), nullable=False),
        sa.Column("carrier", sa.String(length=100), nullable=True),
        sa.Column("tracking_number_encrypted", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["supplier_order_id"],
            ["supplier_orders.id"],
            name=op.f("fk_shipments_supplier_order_id_supplier_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipments")
    op.drop_index(op.f("ix_supplier_orders_external_order_id"), table_name="supplier_orders")
    op.drop_table("supplier_orders")
    op.drop_table("product_supplier_links")
    op.drop_index("ix_stock_history_sku_checked", table_name="product_stock_history")
    op.drop_table("product_stock_history")
    op.drop_index("ix_price_history_sku_checked", table_name="product_price_history")
    op.drop_table("product_price_history")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_messages_external_message_id"), table_name="messages")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_ai_decisions_agent_created", table_name="ai_decisions")
    op.drop_table("ai_decisions")
    op.drop_table("after_sales")
    op.drop_table("xianyu_products")
    op.drop_table("supplier_skus")
    op.drop_table("publication_tasks")
    op.drop_index("ix_orders_account_status_created", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_conversations_account_external", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_supplier_products_snapshot_hash"), table_name="supplier_products")
    op.drop_table("supplier_products")
    op.drop_index(op.f("ix_product_skus_sku_code"), table_name="product_skus")
    op.drop_index(op.f("ix_product_skus_score"), table_name="product_skus")
    op.drop_table("product_skus")
    op.drop_index(op.f("ix_product_scores_total_score"), table_name="product_scores")
    op.drop_index("ix_product_scores_product_created", table_name="product_scores")
    op.drop_table("product_scores")
    op.drop_index("ix_manual_tasks_status_priority", table_name="manual_tasks")
    op.drop_table("manual_tasks")
    op.drop_table("automation_controls")
    op.drop_index("ix_audit_logs_entity_created", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_correlation_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_adapter_calls_correlation_id"), table_name="adapter_calls")
    op.drop_index("ix_adapter_calls_adapter_created", table_name="adapter_calls")
    op.drop_table("adapter_calls")
    op.drop_index("ix_accounts_platform_external", table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_suppliers_code"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_products_lifecycle"), table_name="products")
    op.drop_index(op.f("ix_products_internal_code"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_pricing_rules_category"), table_name="pricing_rules")
    op.drop_table("pricing_rules")
    op.drop_index(op.f("ix_customers_external_customer_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index("ix_jobs_status_schedule", table_name="automation_jobs")
    op.drop_index(op.f("ix_automation_jobs_type"), table_name="automation_jobs")
    op.drop_index(op.f("ix_automation_jobs_correlation_id"), table_name="automation_jobs")
    op.drop_table("automation_jobs")
    # ### end Alembic commands ###
